### ISSUE TITLE
setup-python failing

### ISSUE THREAD

**Issue by lfkdev** [bend-n/godot-template#1]
Since the last change i get the following error when trying to build:
```
Error: Unable to locate executable file: lsb_release. Please verify either the file path exists or the file can be found within a directory specified by the PATH environment variable. Also check the file mode to verify the file is executable.
```

Until yesterday it worked - probably this has todo with [`c44f28ed7ae31067630a3da49a59f26c81e015a0`](https://github.com/bend-n/godot-actions/commit/c44f28ed7ae31067630a3da49a59f26c81e015a0)?

Thanks!

**Comment by bend-n** [comment]
Im aware of this, see https://github.com/actions/setup-python/issues/556

**Comment by bend-n** [comment]
https://github.com/bend-n/godot-actions/commit/c44f28ed7ae31067630a3da49a59f26c81e015a0 was a attempt to fix it.

**Comment by bend-n** [comment]
I could just stop using python completely....

**Comment by bend-n** [comment]
fixed, will close issue in commit after rebasing after making it gd4 compatible

**Comment by bend-n** [comment]
Next time, please create the issue on https://github.com/bend-n/godot-actions, I made issue templates and everything.
